### ISSUE TITLE
Accuracy of Android data

### ISSUE THREAD

**Issue by beckyhilton** [rdlabo-team/capacitor-firebase-analytics#1]
First off thanks for getting this working!

Have you found that using this format to push data into google analytics specifically for android is accurate? I opened it on one samsung phone and it is showing up as 17 different users.  And they are using other types of phones Sony G8441, Google Nexus 5X, Google Pixel 4 etc). I've seen this with the other plugin i was trying as well: https://github.com/stewwan/capacitor-analytics.

**Comment by rdlabo** [comment]
Sorry, I don't know. This is only firebase analytics wrapper. This is maybe firebase analytics issues.
Thanks.
